package:
  name: sosfilt
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ./

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - setuptools_scm[toml]
    - python {{ python }}
    - cython
    - numpy
  run:
    - python
    - scipy

about:
  home: https://github.com/angus-g/sosfilt
  license: MIT
  license_file: LICENSE
  summary: Second-order filtering with multiple filters
